### ISSUE TITLE
Consider adding subjects to orphaned branch messages

### ISSUE THREAD

**Issue by happycollision** [MichaelSims/git-jaspr#180]
The one thing I wish this message also contained was the subject of each HEAD commit. That'd probably make me a touch more confident in what I am about to clean up if there were lots of jaspr branches.

![CleanShot 2023-12-21 at 10 49 18@2x](https://github.com/MichaelSims/git-jaspr/assets/3663628/89cb4ea5-620b-4a1a-9f8e-430db38fb07b)

**Comment by DerelictMan** [comment]
Available in `v17-beta` !
